version: '3.7'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --artifacts-destination ./mlflow/mlruns --host 0.0.0.0
